// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByhphHb7wKxpCJwlL3dQN-WSFK9y9VBqA',
    appId: '1:65456947786:web:f8a009ffa95eb875011cb3',
    messagingSenderId: '65456947786',
    projectId: 'eqraa-book-store',
    authDomain: 'eqraa-book-store.firebaseapp.com',
    storageBucket: 'eqraa-book-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-_DHjwFgwkIzbHvfGAu4dix4sBzn1N1g',
    appId: '1:65456947786:android:ecb0f1be93067acc011cb3',
    messagingSenderId: '65456947786',
    projectId: 'eqraa-book-store',
    storageBucket: 'eqraa-book-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa1gxclls8QDZJR2MtbpVFCSzAeVvp00U',
    appId: '1:65456947786:ios:40fd96ae5147a832011cb3',
    messagingSenderId: '65456947786',
    projectId: 'eqraa-book-store',
    storageBucket: 'eqraa-book-store.firebasestorage.app',
    iosBundleId: 'com.example.eqraaBookStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa1gxclls8QDZJR2MtbpVFCSzAeVvp00U',
    appId: '1:65456947786:ios:40fd96ae5147a832011cb3',
    messagingSenderId: '65456947786',
    projectId: 'eqraa-book-store',
    storageBucket: 'eqraa-book-store.firebasestorage.app',
    iosBundleId: 'com.example.eqraaBookStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByhphHb7wKxpCJwlL3dQN-WSFK9y9VBqA',
    appId: '1:65456947786:web:fefaeed41ffd3804011cb3',
    messagingSenderId: '65456947786',
    projectId: 'eqraa-book-store',
    authDomain: 'eqraa-book-store.firebaseapp.com',
    storageBucket: 'eqraa-book-store.firebasestorage.app',
  );
}
